### ISSUE TITLE
Back button in browser double POST prevention

### ISSUE THREAD

**Issue by openbrian** [qcodo/qcodo#31]
Does QCodo prevent a double POST by using some mechanism like Post/Redirect/Get? This would be useful in search forms.

https://en.wikipedia.org/wiki/Post/Redirect/Get

**Comment by mikeho** [comment]
So it's not really necessary... more often than not, you could use QAjaxAction and QAjaxControlAction (instead of QServerAction and QServerControlAction), and it will execute postBacks via AJAX call, which thus alleviates the problem of the "re-post on refresh" issue.

Look at section #5 (and beyond) in the "QForm and QControl Library" tab in http://examples.qcodo.com/examples/ for specifics.

**Comment by openbrian** [comment]
Would that work with populating QDataGrids?

**Comment by mikeho** [comment]
Yep... there's a "UseAjax" option on QDataGrid that basically does the same thing.  See the examples site for more info.

**Comment by openbrian** [comment]
For search forms which don't post data, we could parameterize method here to be GET.

https://github.com/qcodo/qcodo/blob/master/includes/qcodo/_core/qform/QFormBase.class.php#L911
