### ISSUE TITLE
Frontend for qcodo v0.5.33

### ISSUE THREAD

**Issue by neuroticimbecile** [qcodo/qcodo#34]
Hi Mike,

Good day!
Glad to see more developments on qcodo.
I noticed that codegen doesn't generate CRUD code anymore.
What are you using for frontend for qcodo v0.5.33?
Thank you.

**Comment by mikeho** [comment]
Not sure what you're referring to?  The ORM is still there.

**Comment by neuroticimbecile** [comment]
Hi Mike,

Good day!
Thank you for your reply.
I am sorry for not being clear.
I meant the old qcodo generated "form drafts" for the database.
Does this new version still do that?
If not, what do you use?
Thank you very much!

Regards,
-eric

**Comment by mikeho** [comment]
Ah, I see.  Yeah, so no more QForms or QControls, as Qcodo has been rearchitected to be a microservice/API service layer.  You can utilize any of the other common front-end frameworks for your front end (e.g. React, Vue, Angular, etc.)

Because those front-ends never hit the database directly, but only do so via API calls, it doesn't make sense to have things like form drafts anymore.  Instead, we utilize swagger to write an API layer, and then utilize Qcodo to generate the server components for those API calls, and https://www.npmjs.com/package/@quasidea/oas-client-react to code generate the client components for those API calls.
